<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hypeng.example</groupId>
    <artifactId>board-game-buddy</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>board-game-buddy</name>
    <packaging>pom</packaging>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>25</java.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
<!--        <spring-ai.version>2.0.0-M2</spring-ai.version>
        <springdoc-openapi-starter-webmvc-ui.version>3.0.1</springdoc-openapi-starter-webmvc-ui.version>
        <wiremock-spring-boot.version>4.1.0</wiremock-spring-boot.version>-->
    </properties>
    <modules>
        <module>chaining</module>
        <module>routing</module>
        <module>routing-with-memory</module>
        <module>parallelization</module>
        <module>embabel-games-agent</module>

    </modules>

</project>
