spring:
  application:
    name: board-game-buddy
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true


