spring:
  application:
    name: board-game-buddy
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
      embedding:
        options:
          model: text-embedding-3-small
    vectostore:
      simple:
        store:
          path: ./vectorstore.json
          collection-name: board-game-collection

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true


logging:
  level:
    org:
      zalando:
        logbook: TRACE
logbook:
  format:
    style: http

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env

