spring.application.name=prompt-chaining
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5-nano
boardgame.rules.path=file:///Users/chaud/Documents/BoardGameRules/

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.zalando.logbook=DEBUG
logbook.format.style=http